# Generated by Django 2.2.7 on 2019-11-07 15:46

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserModel',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('sys_id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=127, unique=True)),
                ('phone', models.TextField()),
            ],
            options={
                'db_table': 'users',
            },
            managers=[
                ('objects', accounts.models.MyUserManager()),
            ],
        ),
    ]
